
services:
  public_api:
    build: 
      context: .
      dockerfile: public_api.Dockerfile

    container_name: rag
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:17

    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: rag
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

secrets:
  postgres_password:
    environment: ${POSTGRES_PASSWORD}
