
services:
  public_api:
    build: 
      context: .
      dockerfile: public_api.Dockerfile

    container_name: rag
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres_service
    volumes:
      - .:/app
    restart: always

  postgres_service:
    image: postgres:17

    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rag
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:

